version: "3"

networks:
  auth-network:

services:
  plapp-auth-db:
    image: postgres:latest
    container_name: plapp-auth-db
    ports:
      - "5433:5432"
    env_file:
      - postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - auth-network


  plapp-auth-service:
    image: openjdk:8-jdk-alpine
    container_name: plapp-auth-service
    volumes:
      - .:/auth-service
    ports:
      - 8081:8080
    networks:
        - auth-network
    restart: always
    entrypoint: java -jar /auth-service/target/auth-service-0.0.1-SNAPSHOT.jar

  testbox:
    image: debian:stretch-slim
    entrypoint:
      - /bin/bash
volumes:
  database-data:

